services:
  - type: web
    name: mern-product-store
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && cd frontend && npm ci && npm run build && cd ..
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
